const questionsArray = [
    {
        "question":"What country is called 'Land of Fire and Ice'",
        "option1": "lebanon",
        "option2": "Iceland",
        "option3": "Egypt",
        "option4": "Dennmark",
        "correctAnswer" : "2",
    },
    {
        "question":"What is the official language of the Canadian province Quebec?",
        "option1": "German",
        "option2": "Spanish",
        "option3": "English",
        "option4": "French",
        "correctAnswer" : "4",
    },
    {
        "question":"What nation produces two thirds of the world’s vanilla?",
        "option1": "Nigeria",
        "option2": "Madagascar",
        "option3": "Brassil",
        "option4": "Australia",
        "correctAnswer" : "2",
    },
    {
        "question":"What is the main dialect of Chinese spoken in Hong Kong?",
        "option1": "Cantonese",
        "option2": "Halifax",
        "option3": "Lindisfarne",
        "option4": "Windhoek",
        "correctAnswer" : "1",
    },
    {
        "question":"Which country has the most volcanoes?",
        "option1": "Italy",
        "option2": "Chile",
        "option3": "Greenland",
        "option4": "Indonesia",
        "correctAnswer" : "4",
    },
    {
        "question":"In 1862, the city of Bucharest became the capital of which country?",
        "option1": "Slovakia",
        "option2": "Slovenia",
        "option3": "Romania",
        "option4": "Bulgaria",
        "correctAnswer" : "3",
    },
    {
        "question":"In which country is the ancient city of Petra?",
        "option1": "Saudi Arabia",
        "option2": "Israel",
        "option3": "Palestine",
        "option4": "Jordan",
        "correctAnswer" : "4",
    },
    {
        "question":"Which country formerly ruled Iceland?",
        "option1": "Denmark",
        "option2": "Poland",
        "option3": "England ",
        "option4": "Norway",
        "correctAnswer" : "1",
    },
    {
        "question":"What is the smallest country in the world?",
        "option1": "San Marino",
        "option2": "Vatican City",
        "option3": "Gibraltar",
        "option4": "Malta",
        "correctAnswer" : "2",
    },
    {
        "question":"Cuba is less than a hundred miles away from what U.S. state?",
        "option1": "Florida",
        "option2": "Texas",
        "option3": "Alabama",
        "option4": "Washington",
        "correctAnswer" : "1",
    },
]